#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "schedule.h"
#include "linkedList.h"

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char *argv[]) {
	
	int exit_flag = 0;
	FILE *fp; //우리가 읽어올 schedule.dat. 파일을 담을 변수입니다.
	
	char name[200];
	char place[100], typeName[100];	
	size_t size;
	int month;
	int day;
	int type;
	void *list;
	void *ndPtr;
	void *schedInfo;
	int option;
	int cnt;
	
	//1. FILE pointer open & error handling
	fp = *fopen("schedule.dat", "rb"); //파일경로는 컴퓨터 마다 다르기 때문에 직접 지정을 해주어야 합니다.
	if (fp == NULL)
	{
		printf("경로에 파일이 없습니다. 경로를 확인해 주세요.\n");
		return;
	}
	
	//initializing the list
	printf("Reading the data files... \n");
	list = (void*)list_genList(); //ndPtr 리턴으로 받습니다.
	sched_printTypes();
	
	//2. read from the file
	while (!feof(fp))
	{	
		//fill code here -- generate genSchedInfo structure by genSchedInfo function
	    fscanf(fp,"%s %s %d %d %d", &name[200], &place[100], &type, &month, &day);
        printf("%s %s %d %d %d", name, place, type, month, day); //알맞게 저장되는지 출력해서 확인.
        schedInfo = sched_genSchedInfo(&name, &place, type, month, day);//return 값이 return (void*)schedPtr;
		//put the scheduling info instance generated by genSchedInfo function
		list_addTail(schedInfo, list);
	}
	
	
	//3. close the file pointer
	fclose(fp);
	printf("Read done! %i schedules are read\n", list_len(list));
	
	
	//program starts
	while(exit_flag == 0) 
	{
		//3. menu printing
		printf("\n1. print all the schedules\n");
        printf("2. search for schedules in the month\n");
        printf("3. search for schedules int the place\n");
        printf("4. search for specific type schedule\n");
        printf("5. exit\n");
		
		//4. get option from keyboard
		printf("select an option : ");
		scanf("%d", &option);
		
		
		switch(option)
		{
			case 1: //print all the schedules
				printf("printing all the schedules in the scheduler.....\n\n\n");
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print count and each scheduling info element
                    cnt = 0;//카운트 초기화
                    ndPtr = list_getNextNd(ndPtr); //get the next node from the list
                    schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
                    printf("---------------------------------------\n");
                    printf("%d. Schedule Name : %s (%s)\n", cnt++, schedInfo->name, schedInfo->type);
                    //cnt를 하나씩 출력해줄때 ++ 을 시켜줌으로써 cnt를 증가 시킵니다.
                    printf("When : %d. %d\n", schedInfo->month, schedInfo->day);
                    printf("---------------------------------------\n");
					
					//fill code this part - end
				}
				
				break;
				
			case 2:
				printf("which month ? : ");
				scanf("%i", &month);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the month
                    sched_getMonth();
                    cnt = 0;//카운트 초기화
                    ndPtr = list_getNextNd(ndPtr); //get the next node from the list
                    schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
                    printf("---------------------------------------\n");
                    printf("%d. Schedule Name : %s (%s)\n", cnt++, schedInfo->name, schedInfo->type);
                    //cnt를 하나씩 출력해줄때 ++ 을 시켜줌으로써 cnt를 증가 시킵니다.
                    printf("When : %d. %d\n", schedInfo->month, schedInfo->day);
                    printf("---------------------------------------\n");
					
					//fill code this part - end
				}
				
				break;
				
			case 3:
				printf("which place ? : ");
				scanf("%s", place);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					sched_getPlace(void* obj);
                    //file code here -- print scheduling info elements matching to the place
                    cnt = 0;//카운트 초기화
                    ndPtr = list_getNextNd(ndPtr); //get the next node from the list
                    schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
                    printf("---------------------------------------\n");
                    printf("%d. Schedule Name : %s (%s)\n", cnt++, schedInfo->name, schedInfo->type);
                    //cnt를 하나씩 출력해줄때 ++ 을 시켜줌으로써 cnt를 증가 시킵니다.
                    printf("When : %d. %d\n", schedInfo->month, schedInfo->day);
                    printf("---------------------------------------\n");
					
					//fill code this part - end
				}
				
				break;
				
			case 4:
				printf("which type ?\n");
				sched_printTypes();
				printf("your choice : ");
				scanf("%s", typeName);
				
				if (/* fill code here -- convert the type and check if the type is valid */)
				{
					sched_getType(void* obj);
					ndPtr = list;
					while (list_isEndNode(ndPtr) == 0)
					{
						//file code here -- print scheduling info elements matching to the place
                        cnt = 0;//카운트 초기화
                        ndPtr = list_getNextNd(ndPtr); //get the next node from the list
                        schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
                        printf("---------------------------------------\n");
                        printf("%d. Schedule Name : %s (%s)\n", cnt++, schedInfo->name, schedInfo->type);
                        //cnt를 하나씩 출력해줄때 ++ 을 시켜줌으로써 cnt를 증가 시킵니다.
                        printf("When : %d. %d\n", schedInfo->month, schedInfo->day);
                        printf("---------------------------------------\n");
						
						//fill code this part - end
					}
				}
				else
				{
					printf("wrong type name!\n");
				}
				break;
				
			case 5:
				printf("Bye!\n\n");
				exit_flag = 1;
				break;
				
			default:
				printf("wrong command! input again\n");
				break;
		}
		
		
	}
	
	return 0;
}
